### ISSUE TITLE
Allow arenas to be shipped with associated config

### ISSUE THREAD

**Issue by mdsimmo** [mdsimmo/bomberman#31]
**What problem does the feature solve**
If an arena is created that requires a specific config (e.g starting kit, loot drops), then two files are needed to be shipped to distribute the game (both config and schematic). This extra file adds unwanted complexity.

**Describe the solution you'd like**
Make I to possible to ship config and schematic in a single zip file.

**Describe alternatives you've considered**
* Put the schematic inside the config file (eww)

**Questions still to answer**
* ~~Does a new game generate a new config, or just link the schematic config~~ Generate new config
* ~~If linking config files is chosen, we could also have new games linked to the main config instead of copying everything out (that wasn't a question)~~
* ~~Can a game overwrite the schematic config?~~ yes
* ~~How to let users produce a config/schematic zip easily? Just zipping the files won't work since the config won't point to the correct schematic file path~~ It generates by default
* ~~Does a config/schematic zip contain a full config? What does it default to if not a full config?~~ A full config
* ~~What directory to store the config/schematic zips?~~ in the game saves folder
* ~~Need a better name than "config/schematic zip".~~ Just game save will work

**Tasks**
- [x] Save all game data in a zip file
- [x] Add code to automatically update old saves
- [x] Allow `/bm create` to copy an existing config
- [x] Replace built-in schematic with a built-in game save (thus removing the need for default config)
- [x] Remove default game config from settings

**Comment by mdsimmo** [comment]
It'd be kinda nice if all games are stored in a zip file (i.e.all games copy their schematic on creation). It'd take more dial space, but then there would be no problems with deleting old schematics or changing file structure.

**Comment by mdsimmo** [comment]
Included in v0.8.0
